### ISSUE TITLE
Running on arm64?

### ISSUE THREAD

**Issue by kuenkin** [ShiromMakkad/LedFxDocker#4]
Hello, 
I would like to run this docker in the architecture arm64, is it possible?
What would  be the steps to manage it?
Best regards

**Comment by ShiromMakkad** [comment]
You can run it on a Pi4 running an arm64 OS, but I haven't been able to compile it with 64 bit because of Cython issues.

**Comment by kuenkin** [comment]
I got this error when trying to pull on arm64:
No matching manifest for linux/arm64/v8 in the manifest list entries

By the way, I was able to run it in Coreelec (which is armv7 image) with a S905w and it works very well getting the sound from a snapcast server.

**Comment by kuenkin** [comment]
Hello, 
I was able to build it on arm64 and it runs.
The problem now is the snapcast client and the architecture, can not run armhf, so I will try to modify snapcast.sh to use a local deb I have and build it again.

**Comment by ShiromMakkad** [comment]
Howd you get Cython to build on arm64?

**Comment by kuenkin** [comment]
Well, I didn't do any special as far as I remember I just compile the whole thing following your instructions in a Debian 11 system

**Comment by ShiromMakkad** [comment]
Just added arm64 support
