### ISSUE TITLE
Having issues connecting to Snapcast Server / Mopidy

### ISSUE THREAD

**Issue by acidrs03** [ShiromMakkad/LedFxDocker#6]
Hello I have Mopidy and Snapcast running in docker and wanted to get this LedFx container setup to work with them but am having a couple of issues.

My Mopidy has an audio output that is 
`output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! filesink location=/tmp/snapfifo`

From what i can tell this LedFx container is looking for an output in a file called stream. So if i change the Mopidy out to 
`output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S32LE ! filesink location=/tmp/stream`

LedFx  can access that, however that then renders my snapcast unavailable as it is wanting snapfifo.

So my question is how would i get this all working together, what files do i need to edit to have this all work in sync. If this is a mopidy config file setting, and someone has an example i can look at that would be great. I'm just a little confused at how this all works together.

**Comment by ShiromMakkad** [comment]
I'm pretty sure you can send Mopidy directly into Snapcast, so what you'd want to do is `Mopidy -> Snapcast -> LedFxDocker`. To connect Snapcast and LedFxDocker, use the `HOST` environment variable. Don't set the `FORMAT` environment variable, so you don't need to actually use the stream file that LedFxDocker creates.

**Comment by ShiromMakkad** [comment]
Check out the `examples/stream` folder. There's a dockerfile that has LedFx, Mopidy, Snapcast, and Shairport sync all working together and documented. Credits to Spiro-C
