### ISSUE TITLE
LedFx v0.10.7 is out currently running version: v.0.10.5

### ISSUE THREAD

**Issue by Pr0mises** [ShiromMakkad/LedFxDocker#7]
Hey, thanks for that amazing project. 
You saved me a few more weeks figuring everything out!

There are new versions of LedFX, do you compile them yourself and upload the images to docker or is it a broken automatic build?

**Comment by ShiromMakkad** [comment]
I have a couple Github workflows that I run to update it. I just ran them, so if they succeed, we're good.

Thanks for the heads up

**Comment by ShiromMakkad** [comment]
The latest tag is working and pushed. The dev tag failed, so I'll need to look at it

**Comment by Pr0mises** [comment]
Thank you!
