### ISSUE TITLE
Run LedFX with USB sound card

### ISSUE THREAD

**Issue by ambarusa** [ShiromMakkad/LedFxDocker#8]
Hi, could you help me how to use your image with an external USB sound card? I went through your examples, but I got nothing.

Thanks very much.

**Comment by ShiromMakkad** [comment]
You'll have to handle that yourself based on the system you're using. You should use the named pipe input for that, you might be able to use something like ffmpeg to read the output of your usb soundcard and write it to the named pipe input, but I haven't tried doing this.
