### ISSUE TITLE
Update snapclient version

### ISSUE THREAD

**Issue by Schluggi** [ShiromMakkad/LedFxDocker#9]
Hi,

big thanks for the Snapcast-Integration 👍

Could you update the Dockerfile to use always the latest upstream version of Snapclient (0.26.0 at the moment)?
Currently the Dockerfile uses apt which result in an old version (0.15.0).

**Comment by ShiromMakkad** [comment]
I'm moving rn and my laptop is broken so it might be a while but yea I can update it
